### ISSUE TITLE
Custom output dir

### ISSUE THREAD

**Issue by aphofstede** [swiniak/testcafe-testcafe-reporter-chrome-recorder#2]
This is awesome. Hope it captures some screens before my headless process runs into this unspecified error I'm getting.
I'm running it in a remote Docker container though, looks like I can't access `/tmp/chrome-recorder/` in my environment, could the output dir be made configurable?

**Comment by andrzej-woof** [comment]
Ok, I'll add env variables for temp and output paths.

**Comment by andrzej-woof** [comment]
Hey @aphofstede 
Published - description in readme.

**Comment by aphofstede** [comment]
Awesome, thanks. 
It does print a 0B file called "null" in the run dir in my case (and a single white screenshot in a subdir) This is a TestCafé headless Chrome issue I'm having, but might indicate you'd want a sanity check before writing the final video in a fail situation.

**Comment by andrzej-woof** [comment]
The null file is probably because i've made mistake in previous readme saying `chrome-recorder:null` while it should be `/dev/null` (since I don't actually write any report file).

Single white screenshot would probably mean there wasn't any change - I believe (although could be wrong) that chrome only captures frames if there is any change in the displayed page. Weird cause I'd expect at least testcafe loader page there.

If testcafe fails to completely I wont be able to generate video anyway since the reporter will not be called (unless I'd do some shutdown hook which I don't think is a good idea here), that's why I've left the frames. 

As for your issue ( https://github.com/DevExpress/testcafe/issues/2194#issuecomment-423771565 ) have you tried this DEBUG env variable? https://github.com/DevExpress/testcafe/wiki/Debugging-TestRun

**Comment by aphofstede** [comment]
Thanks! I wasn't aware of that debug mode. Though it didn't really output anything useful, I did discover the root problem is a redirect loop in my nginx config. Not sure why yet..
